### ISSUE TITLE
Changer les logos pour 2016

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/callForPaper#1]
Pour les emails:
- http://cfp.gdgnantes.com/lib/images/footer.png
- https://cfp.gdgnantes.com/lib/images/header.png

**Comment by xavmarc** [comment]
Valider avec @bpetetot s'il ne trouve pas mieux pour le header des mails que celui que j'ai fait
![header](https://cloud.githubusercontent.com/assets/5824142/15143742/8a26a92e-16ab-11e6-936a-99153a30b894.png)

**Comment by jlandure** [comment]
@xavmarc T'es sûr de toi pour le footer en blanc sur blanc ?

**Comment by xavmarc** [comment]
Le footer est bien en blanc mais le fond est gris (background-color: #555555)

**Comment by jlandure** [comment]
Ok faudra mettre une capture d'écran de ce que rend l'email.

**Comment by jlandure** [comment]
@bpetetot go !

**Comment by jefBinomed** [comment]
l'image du  footer est hyper pixelisée :(

**Comment by jlandure** [comment]
LGTM
<img width="541" alt="capture d ecran 2016-05-29 a 23 20 41" src="https://cloud.githubusercontent.com/assets/525974/15636087/fd0d0012-25f3-11e6-91e1-62c11f52756e.png">
