### ISSUE TITLE
Enlever la faille xss

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/callForPaper#13]
- https://github.com/breizhcamp/callForPaper/commit/e63026c4bdd8f464ac9e12f21dd3baa6f459e70b
- https://github.com/breizhcamp/callForPaper/commit/2814355056d687f9be31055c4a3e588e95297a33
- https://github.com/breizhcamp/callForPaper/commit/cfd0b524121c33c83a63e4000a8a14a79793526d

**Comment by jefBinomed** [comment]
Pour ma part je penses que c'est un échec...
![erreur_script_cfp](https://cloud.githubusercontent.com/assets/681267/15194526/978cad84-17c3-11e6-8e08-91031f76bfef.png)

**Comment by jlandure** [comment]
ok et sinon si tu fais `<script></script>` ?

**Comment by jefBinomed** [comment]
ça marche pas plus :(

**Comment by jlandure** [comment]
Ca marche pas. ok comment ça ? tu as une erreur dans la console ?

**Comment by jefBinomed** [comment]
et c'est quelque soit le champ markdown en fait, j'ai fait des variations pour voir si c'était lié à un champ mais non. En fait, je sais que ça marche pas car quand je suis en tant que speaker, je peux pas lire les détails de mon talk s'il y a des scripts, tout est cassé. Alors que si j'édites le spreadsheet et que je vires les scripts, je peux accéder à ma fiche de talk

**Comment by jlandure** [comment]
oui c'est normal ça.
C'est le principe pour bloquer la faille XSS : si tu marques
<script>test</script> bio, tu ne verras que "bio" dans le résultat affiché
à l'écran pour ne pas exécuter de code malicieux.

**Comment by jefBinomed** [comment]
non la moi c'est pire : regarde : 
avec script
![avec_script](https://cloud.githubusercontent.com/assets/681267/15194855/603c9af4-17c5-11e6-9bdd-f87d659ff7eb.png)

sans script
![sans_script](https://cloud.githubusercontent.com/assets/681267/15194856/605278c4-17c5-11e6-8a2f-fefc0479d7e6.png)

**Comment by jlandure** [comment]
tu as quoi dans la console ?...

**Comment by jefBinomed** [comment]
la même erreur que dessus

**Comment by jlandure** [comment]
oui mais c'est normal du coup car c'est pas du html valide que tu as
écrit... viens sur slack stuve...

**Comment by jlandure** [comment]
à tester : `<script>alert(123)</script>`

**Comment by jefBinomed** [comment]
Toujours pareil :( la page côté édition de session m'affiche tout vide avec l'erreur JS dans la console
