### ISSUE TITLE
Ajouter le champ "message pour le comité"

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/callForPaper#21]
Aujourd'hui nous avons `Références ou compléments d'informations`
Et il faudrait plutôt indiquer `Message pour le comité / Références / Compléments d'informations`

**Comment by pguyard** [comment]
voir diviser en plusieurs champs

Pierrick Guyard

**Comment by jlandure** [comment]
_relou_ car faut changer le modèle appengine + le spreadsheet derrière...

**Comment by pguyard** [comment]
pour l'année prochaine ?

Pierrick Guyard

**Comment by jlandure** [comment]
bah c'est pas méchant de changer un libellé 👍

**Comment by jlandure** [comment]
obsolete: won't fix
