### ISSUE TITLE
Les champs markdown ne s'affichent pas correctement dans l'onglet Talk

### ISSUE THREAD

**Issue by hgwood** [GDG-Nantes/callForPaper#22]
Tous les retours chariot ont l'air d'avoir été supprimés avant de passer le parser markdown.

![image](https://cloud.githubusercontent.com/assets/1656170/18070782/8d21f776-6e50-11e6-8802-4543585cbb75.png)

**Comment by jlandure** [comment]
obsolete: won't fix
