### ISSUE TITLE
Vérifier l'url code of conduct

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/callForPaper#8]
http://devfest.gdgnantes.com/cod existe-elle en 2016 ?

**Comment by xavmarc** [comment]
Changement de l'URL : http://devfest.gdgnantes.com/cod.html
A vérifier quand le site sera en ligne

**Comment by jlandure** [comment]
Mais non ça on peut regler sur appengine pour que http://devfest.gdgnantes.com/cod => http://devfest.gdgnantes.com/cod.html

**Comment by jlandure** [comment]
bon on laisse cod.html si c'est bien ça qui est prévu 👍
